import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#fff",
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: 5,
    marginRight: 60,
    marginBottom: 15,
    marginTop: 30,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  columnHeaderHistorico: {
    width: 150,
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    color: "#2C4B4E",
  },
  columnHeaderData: {
    width: 100,
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    color: "#2C4B4E",
  },
  columnHeaderBotao: {
    width: 40,
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    color: "#2C4B4E",
  },
  historico: {
    width: 150,
    height: 40,
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
    lineHeight: 40,
    color: "#2C4B4E",
    backgroundColor: "#f5f5f5",
    borderRadius: 10,
  },
  data: {
    width: 100,
    height: 40,
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
    lineHeight: 40,
    color: "#2C4B4E",
    backgroundColor: "#f5f5f5",
    borderRadius: 10,
  },
  botao: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5f5f5",
    borderRadius: 5,
  },
  icone: {
    width: 25,
    height: 25,
  },
  listContent: {
    paddingVertical: 10,
  },
  arrow: {
    width: 30,
    height: 30,
  },
  header: {
    fontSize: 26,
    fontWeight: "bold",
    textAlign: "center",
    color: "#2C4B4E",
  },
  inputInfos: {
    marginBottom: 100,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  inputPeso: {
    width: 150,
    height: 40,
    borderColor: "#00AD71",
    borderWidth: 2,
    borderRadius: 10,
    textAlign: "center",
    color: "#2C4B4E",
    fontSize: 14,
  },
  inputData: {
    width: 100,
    height: 40,
    borderColor: "#00AD71",
    borderWidth: 2,
    borderRadius: 10,
    textAlign: "center",
    color: "#2C4B4E",
    fontSize: 14,
  },
  addButton: {
    width: 40,
    height: 40,
    backgroundColor: "#00AD71",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  addButtonText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
  },
  spacer: {
    flex: 1,
  },
  continuebutton: {
    height: 60,
    borderRadius: 25,
    backgroundColor: "#00AD71",
    justifyContent: "center",
    alignItems: "center",
    marginBottom:80,
    marginTop:25,
  },
  buttonText: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#ffffff",
    alignItems: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    width: "80%",
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
    color: "#2C4B4E",
  },
  input: {
    width: "100%",
    height: 50,
    borderWidth: 2,
    borderColor: "#00AD71",
    borderRadius: 15,
    paddingLeft: 10,
    marginBottom: 15,
    textAlign:"center"
  },
  modalButtonText: {
    color: "#fff",
    fontSize: 18,
    textAlign: "center",
  },
  modalButton: {
    width: "100%",
    backgroundColor: "#00AD71",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginTop: 10,
  },
  modalCloseButton: {
    width: "100%",
    backgroundColor: "#FF725E",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginTop: 10,
  },
  datePickerButton: {
    width: "100%",
    height: 50, // Altere conforme necessário
    borderWidth: 2,
    borderColor: "#00AD71",
    borderRadius: 15,
    justifyContent: "center", // Para centralizar verticalmente
    alignItems: "center", // Para centralizar horizontalmente
    marginBottom: 15,
  },
  datePickerText: {
    textAlign: "center",
    fontSize: 16, // Ajuste o tamanho conforme necessário
    color: "#2C4B4E", // Altere a cor se necessário
  },
});

export default styles;
